### ISSUE TITLE
RuntimeError: Requested MovieWriter (ffmpeg) not available

### ISSUE THREAD

**Issue by petermisovic** [fabincarmo/vidwav#1]
Hello, would you be so kind to help me. I trying to run you script resulting with following issue: 
Traceback (most recent call last):
  _File "d:\_devel\vidwav\vidwav.py", line 26, in vidwav
    FFMpegWriter = manimation.writers['ffmpeg']
  File "C:\Users\thailon\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\animation.py", line 151, in __getitem__
    raise RuntimeError(f"Requested MovieWriter ({name}) not available")
RuntimeError: Requested MovieWriter (ffmpeg) not available_

I do have ffmpeg installed (Version: 1.4), as well as matplotlib (Version: 3.5.1). I'm using Python 3.10.1. 

Thank you!

**Comment by petermisovic** [comment]
> Hello, would you be so kind to help me. I trying to run you script resulting with following issue: Traceback (most recent call last): _File "d:_devel\vidwav\vidwav.py", line 26, in vidwav FFMpegWriter = manimation.writers['ffmpeg'] File "C:\Users\thailon\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\animation.py", line 151, in **getitem** raise RuntimeError(f"Requested MovieWriter ({name}) not available") RuntimeError: Requested MovieWriter (ffmpeg) not available_
> 
> I do have ffmpeg installed (Version: 1.4), as well as matplotlib (Version: 3.5.1). I'm using Python 3.10.1.
> 
> Thank you!

I have fixed it this way:
_#FFMpegWriter = manimation.writers['ffmpeg']
metadata = dict(title='Wav Spectrogram', artist='Matplotlib', comment='')
writer = manimation.FFMpegWriter(fps=fps, metadata=metadata, bitrate=3500)_

**Comment by angry-birb** [comment]
Hey, How did you solve this error? 
Any help is appreciated, thank you.
